<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDLSxvHX\Tests_Sylius_Ux_Application_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDLSxvHX/Tests_Sylius_Ux_Application_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerDLSxvHX.legacy');

    return;
}

if (!\class_exists(Tests_Sylius_Ux_Application_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerDLSxvHX\Tests_Sylius_Ux_Application_KernelTestDebugContainer::class, Tests_Sylius_Ux_Application_KernelTestDebugContainer::class, false);
}

return new \ContainerDLSxvHX\Tests_Sylius_Ux_Application_KernelTestDebugContainer([
    'container.build_hash' => 'DLSxvHX',
    'container.build_id' => 'ac97b536',
    'container.build_time' => 1656504999,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDLSxvHX');
